#pragma once

/* 무기 */
#define WEAPON_PINK_CAT_BLADE 1
#define WEAPON_PAL_SPHER 2
#define WEAPON_BOW 3

/* 아이템 */
#define ITEM_ARROW 10
#define ITEM_WOOD 11
#define ITEM_ROCK 12
#define ITEM_PALJIUM 13

/* 건물 */
#define ARCHITECTURE_PALBOX 20
#define ARCHITECTURE_WORKBENCH 21
#define ARCHITECTURE_PALBED 22
#define ARCHITECTURE_DEFENCE_WOOD_WALL 23
#define ARCHITECTURE_WOOD_WALL 24
#define ARCHITECTURE_WOOD_DOOR 25
#define ARCHITECTURE_BED 26
#define ARCHITECTURE_TABLE 27